# Stage 1: Build
FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

# copy csproj and restore dependencies
COPY *.sln ./
COPY API/*.csproj ./API/
RUN dotnet restore ./API/API.csproj

# copy everything else and build
COPY . .
WORKDIR /src/API
RUN dotnet publish -c Release -o /app/publish/p:UseAppHost=false

# Stage 2: Run
FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENV ASPNETCORE_ENVIRONMENT=Development
ENTRYPOINT ["dotnet", "API.dll"]
